### ISSUE TITLE
Please bump version

### ISSUE THREAD

**Issue by mlaurense** [Billinkbv/Magento-2#31]
Composer is still serving 2.0.1 because the version number is not raised. See #23 and #24 as this is not the first time this has happened

**Comment by Billinkbv** [comment]
Done

**Comment by mlaurense** [comment]
@Billinkbv no it is not. Same problem as in #24 I am still getting the old version because the latest commit isn't in the last version.

**Comment by Billinkbv** [comment]
@mlaurense Sorry for the inconvience. I asked our supportpartner to take a look at this issue. I will come back to this when I have a reaction.
